layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = xray on, match:namespace waybar

layerrule = blur on, match:namespace logout_dialog
layerrule = animation popin 95%,match:namespace logout_dialog

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = animation popin 95%,match:namespace rofi
# layerrule = unset, rofi

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-control-center
# layerrule = ignorezero true,match:namespace swaync-control-center
layerrule = animation popin 95%, match:namespace swaync-control-center

# layerrule = blur, swaync-notification-window
# layerrule = ignorezero, swaync-notification-window
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = animation slide, match:namespace swaync-notification-window

